### ISSUE TITLE
maybe support `|` delimited rawstrings

### ISSUE THREAD

**Issue by reuleaux** [lloda/guile-raw-strings#1]
Hi,

maybe be more liberal and support `|` as a delimiter as well - this seems most natural to me,
like so:
```
#R|some raw string|
```
and ideally - for ease of typing (and similar to Python): (miniscule) `r` instead of `R` as well, like so:
```
#r|some raw string|
```
Thanks,
  -A

**Comment by lloda** [comment]
Hey,

I've made some changes to make these things easier to configure – you just have to edit `openc`, `closec`, and `extension-char` in `mod/raw-strings.scm`.

Regards.

**Comment by reuleaux** [comment]
OK, thanks a lot, I will have a look (soon i.e.)

**Comment by reuleaux** [comment]
OK, I have tried it, and it seems to work, thanks again:

Thus I have used:
```scheme
(eval-when (expand load eval)
  (define openc "|([\"")
  (define closec "|)]\"")
  ;;(define extension-char #\R)
  (define extension-char #\r)
  )
```

So it's either one of those opening chars (closing chars), but only one extension char: `#\r` in my case, not both: `#\r` and `#\R`, right ?

**Comment by lloda** [comment]
Right. I mean you can easily have both if you want – just don't use extension-char and replace the last line

```
(read-hash-extend extension-char reader-extension-raw-string)
```

by

```
(read-hash-extend #\r reader-extension-raw-string)
(read-hash-extend #\R reader-extension-raw-string)
```
