### ISSUE TITLE
Tagged Release?

### ISSUE THREAD

**Issue by yewscion** [lloda/guile-raw-strings#2]
Hello!

Would it be possible to get a tagged release set up for this library? I find myself using it all of the time, but can't submit a packaged version to various package managers (Brew, etc) without a version number to package.

It seems relatively stable, so even just adding the release tag of 1.0.0 would be enough to overcome this issue, and allow more people to use this very useful piece of software!

**Comment by lloda** [comment]
Hello! 

I tagged the current head `v1.0.0`. Let me know if that works (or not).

Thanks

**Comment by yewscion** [comment]
That works great! Thank You!
